# Generated by Django 5.1.3 on 2024-11-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciolegal',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asesorialegal',
            name='especialidad',
            field=models.CharField(db_column='especialidad', max_length=255),
        ),
        migrations.AlterField(
            model_name='asesorialegal',
            name='num_asesorias',
            field=models.IntegerField(db_column='num_asesorias'),
        ),
        migrations.AlterField(
            model_name='divorcio',
            name='duracion_estimada',
            field=models.DecimalField(db_column='duracion_estimada', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='divorcio',
            name='num_divorcios',
            field=models.IntegerField(db_column='num_divorcios'),
        ),
        migrations.AlterField(
            model_name='serviciolegal',
            name='costo',
            field=models.DecimalField(db_column='costo', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviciolegal',
            name='descripcion',
            field=models.CharField(db_column='descripcion', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviciolegal',
            name='nombre_servicio',
            field=models.CharField(db_column='nombre_servicio', max_length=255, unique=True),
        ),
    ]
